// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlxqmrahvxbeauwsyydw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpseHFtcmFodnhiZWF1d3N5eWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzE3MDcsImV4cCI6MjA2NDMwNzcwN30.hqBbKfABNaUBh0qdr4Zm0m7qjfT3211JbTZADAXvkVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);